ALIGNMENTS = ["Ally", "Enemy"]
NAMES = ["Death Star", "Millenium Falcon", "Star Destroyer", "Normandy SR-2", "Unreliable"]
CLASSES = ["Corvette", "Frigate", "Cruiser", "Destroyer", "Carrier", "Dreadnought"]
FIRST_NAMES = ["Michael", "Dwight", "Jim", "Pam"]
SECOND_NAMES = ["Scott", "Schrute", "Halpert", "Beesly"]
RANKS = ["Captain", "Admiral", "Commander"]
