# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galaxy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgalaxy.proto\x12\x04\x65x01\" \n\x11GalacticPossition\x12\x0b\n\x03pos\x18\x01 \x03(\x02\"\x9c\x03\n\x04Ship\x12\x31\n\talignment\x18\x01 \x02(\x0e\x32\x18.ex01.Ship.AlignmentType:\x04\x41lly\x12\x15\n\x04name\x18\x02 \x02(\t:\x07Unknown\x12(\n\nship_class\x18\x03 \x02(\x0e\x32\x14.ex01.Ship.ClassType\x12\x0e\n\x06length\x18\x04 \x02(\x02\x12\x11\n\tcrew_size\x18\x05 \x02(\x05\x12\r\n\x05\x61rmed\x18\x06 \x02(\x08\x12$\n\x08officers\x18\x07 \x03(\x0b\x32\x12.ex01.Ship.Officer\x1a@\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x13\n\x0bsecond_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"$\n\rAlignmentType\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"`\n\tClassType\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05*e\n\tTaskState\x12\r\n\tTASK_OPEN\x10\x00\x12\x14\n\x10TASK_IN_PROGRESS\x10\x01\x12\x13\n\x0fTASK_POST_PONED\x10\x02\x12\x0f\n\x0bTASK_CLOSED\x10\x03\x12\r\n\tTASK_DONE\x10\x04\x32>\n\x06Galaxy\x12\x34\n\tget_ships\x12\x17.ex01.GalacticPossition\x1a\n.ex01.Ship\"\x00\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'galaxy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKSTATE']._serialized_start=471
  _globals['_TASKSTATE']._serialized_end=572
  _globals['_GALACTICPOSSITION']._serialized_start=22
  _globals['_GALACTICPOSSITION']._serialized_end=54
  _globals['_SHIP']._serialized_start=57
  _globals['_SHIP']._serialized_end=469
  _globals['_SHIP_OFFICER']._serialized_start=269
  _globals['_SHIP_OFFICER']._serialized_end=333
  _globals['_SHIP_ALIGNMENTTYPE']._serialized_start=335
  _globals['_SHIP_ALIGNMENTTYPE']._serialized_end=371
  _globals['_SHIP_CLASSTYPE']._serialized_start=373
  _globals['_SHIP_CLASSTYPE']._serialized_end=469
  _globals['_GALAXY']._serialized_start=574
  _globals['_GALAXY']._serialized_end=636
# @@protoc_insertion_point(module_scope)
